stages:
  - build
  - deploy

build:
  stage: build
  image: node
  artifacts:
    paths:
      - sell_me_out/dist/
  cache:
    paths:
      - sell_me_out/dist/
  script:
    - cd sell_me_out
    - npm install
    - npm run build

deploy:
  stage: deploy
  image: debian
  environment:
    name: sellmeout-front
    url: https://sellmeout.alexis-bonal.fr
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -ae ssh ./sell_me_out/dist/sell_me_out/* gitlab-deploy@alexis-bonal.fr:sellmeout-front
  dependencies:
    - build
